name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #gerar tag de acordo com o commit or something

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      # because of setup go i have access of running the Go commands
      #
      - name: Run test
        run: go test

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c 7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            marceloarraes31/journey-api:${{steps.generate_sha.outputs.sha}}
            marceloarraes31/journey-api:latest

      # - name: Build docker image
      #   run: docker build -t marceloarraes31/journey-api:${{steps.generate_sha.outputs.sha}} .

      # - name: Push image
      #   run: |
      #     docker push marceloarraes31/journey-api:${{steps.generate_sha.outputs.sha}}
      #     docker tag marceloarraes31/journey-api:${{steps.generate_sha.outputs.sha}} marceloarraes31/journey-api:latest
      #     docker push marceloarraes31/journey-api:latest

# logar no container registry
# enviar imagem apos

# Actions abstract commands and using actions instead of
# direct commands is a good practice.

